DM-22531: AuxTel on-sky testing Dec/2019
lsst-ts/ts_notebooks pull request #10
Opened 2019-12-18 20:21 UTC by tribeiro

Add notebooks developed during operations. (+4 squashed commits)
Squashed commits:
[5a229ab] Add quick rotator test script.
[0b6239d] Add Basic Rotator test notebook
[da73e77] Add end-to-end verification notebook. Add ATSpectrograph notebook.
[68e53be] Add example notebook with how to get data from influxdb EFD

2019-12-18 20:47 UTC, patrickingraham requested changes

2019-12-18 20:47 UTC, patrickingraham commented on examples/AT start up.ipynb
> +    "This notebook contains a template for basic startup operations for the Auxiliary telescope. At the begging of the night a user can run the startup procedure to prepare the telescope for observin
Typos: 
beginning, once

2019-12-18 20:47 UTC, patrickingraham commented on examples/AT start up.ipynb
> +    "%%script bash \n",
Maybe just explain when it is required to do this. Maybe put it in a separate cell and say, "uncomment and run if IDL files don't exist" or something like that.

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "If the ATMCS is not enable run the next cell."
enabled,

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "The next cell sets the observatory location. This is needed to compute the Az/El of the target to set the camera rotation angle. We are trying to keep the angle close to zero. "
which angle? no obvious from the next cell....

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "    rotPA=180.-alt_az.alt.deg,\n",
Say this is where the rotator position is optimized to be near zero. Also say what would be the default value if you weren't trying to set it near zero

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "If you want to make persistet offsets you can use the following method. "
I don't really understand this. What do you mean by persistent and when would I want to do that?

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "If you want to add your offset to a pointing model file, do the following. "
Is this really part of a standard slew? It feels outside the scope of a slew example. Might belong in a "create a pointing model" example?

2019-12-18 20:47 UTC, patrickingraham commented on examples/Go2Target.ipynb
> +    "await attcs.slew(ra=\"20:25:38.85705\", \n",
why is this here?

2019-12-18 20:47 UTC, patrickingraham commented on examples/Make_Grid.ipynb
> +    "## Disable auto download of iers data. "
One might say  what iers data is in brackets....

2019-12-18 20:47 UTC, patrickingraham commented on examples/Make_Grid.ipynb
> +    "Obervatory location (lon, lat and height extracted from: https://github.com/lsst/sims_utils)"
*Observatory

2019-12-18 20:47 UTC, patrickingraham commented on examples/Make_Grid.ipynb
> +    "for i in range(10):\n",
I must be really daft but I don't see how this is changing targets. I don't see any offset that is iterated over...

2019-12-18 20:47 UTC, patrickingraham commented on examples/Make_Grid.ipynb
> +    "await atptg.cmd_azElTarget.set_start(azDegs=0., elDegs=80.)"
Why is this here? it parks the telescope...

2019-12-18 21:29 UTC, tribeiro commented
I think I covered the last comments on the PR.

2019-12-19 16:09 UTC, patrickingraham approved these changes
Looks much better!

2020-03-06 18:18 UTC, merged