Tickets/dm 32025
lsst-ts/ts_notebooks pull request #57
Opened 2021-10-04 15:23 UTC by edennihy

Hi folks, following our discussion at the tagup on Friday 2021-10-01, I created a directory structure to store the individual test notebooks we have executed as part of LVV-P81. The notebooks are setup as standalone tests and are designed to mirror the structure of the JIRA execution as closely as possible. Any comments are welcome!

2021-10-05 23:53 UTC, b1quint requested changes
I agree with this new directory structure. Before we merge, you might want to clear the outputs of `procedures/LVV-P81/LVV-C176/LVV-T2193.ipynb`. The other two are Ok.

2021-10-07 17:29 UTC, hdrass commented on procedures/LVV-P81/LVV-C176/LVV-T2190.ipynb
> +{
<p>I know it is tempting to use the Step numbers to make the relation between the Test case  and the corresponding notebook. </p><p>The issue with this that we the step numbers might be changing when executing a test case or updating a test case. This is mainly because we are calling in test steps from other test cases at execution time or we are updating a test case during execution. </p><p>I would to give one or more test steps at title and refer in the notebook to the tile of the test steps.</p><p>I think it is ok to leave it like this here but start to do so in the future.</p><p> </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/lsst-ts/ts_notebooks/pull/57/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-10-08 00:03 UTC, edennihy commented
@b1quint, change request addressed in commit 5dc731c

2021-10-08 00:09 UTC, b1quint approved these changes

2021-10-08 01:04 UTC, edennihy commented on procedures/LVV-P81/LVV-C176/LVV-T2190.ipynb
> +{
That makes sense, and in fact, almost all of the test step titles/descriptions are already in the notebook so can already provide the structure needed to quickly navigate between steps. I have removed the Step numbers and instead added horizontal lines to delineate between execution steps in commit 09acb82 

Let me know what you think!

2021-10-14 14:36 UTC, tribeiro approved these changes
Hi @edennihy I think these are good to go. I liked the organization of the directories as well.. But please, see my comments before merging...

2021-10-15 18:27 UTC, merged