Tickets/dm 34662
lsst-ts/ts_notebooks pull request #82
Opened 2022-05-06 01:16 UTC by patrickingraham

2022-05-12 14:45 UTC, isotuela commented
I've added comments in ReviewNB app, but can't see how to submit them from that app. I think this will do it. Apologies!

2022-05-12 14:55 UTC, isotuela requested changes
Stellar.

2022-05-17 00:19 UTC, patrickingraham commented
made most changes and responded to comments. Note that the comments seem to be a bit scrambled so I might have misinterpreted or misunderstood something.

2022-05-25 05:21 UTC, isotuela approved these changes

2022-05-25 05:27 UTC, merged